vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        customer:
            uri_prefix: /uploads/logos
            upload_destination: '%kernel.project_dir%/public/uploads/logos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        caseStudy:
            uri_prefix: /uploads/caseStudiesImages
            upload_destination: '%kernel.project_dir%/public/uploads/caseStudiesImages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer